import sqlite3
conn = sqlite3.connect('mis_reports.db')
cur = conn.cursor()
cur.execute("SELECT COUNT(*) FROM techno_param_master WHERE group_code='BOF'")
print('BOF remaining:', cur.fetchone()[0])
cur.execute("SELECT COUNT(*) FROM techno_param_master WHERE group_code='SMS'")
print('SMS current:', cur.fetchone()[0])
cur.execute("SELECT section, COUNT(*) FROM techno_param_master WHERE group_code='SMS' AND section='TMI' GROUP BY section")
print('SMS/TMI rows:', cur.fetchall())
cur.execute("SELECT COUNT(*) FROM techno_param_master WHERE group_code='MAJOR' AND section IN ('Hot Metal Consumption','Scrap Consumption','TMI')")
print('MAJOR HMS/Scrap/TMI still there:', cur.fetchone()[0])
conn.close()
