"""One-off seeder: techno parameter master + sample monthly values + targets.
Bases taken from the OMI Aug'25 report PDF. Safe to re-run (upserts)."""
import db

# (group, section, row_label, unit, sort, base_value)
ROWS = [
    # MAJOR
    ("MAJOR", "Coal to Hot Metal", "BSP", "", 1, 0.948),
    ("MAJOR", "Coal to Hot Metal", "DSP", "", 2, 0.986),
    ("MAJOR", "Coal to Hot Metal", "RSP", "", 3, 0.881),
    ("MAJOR", "Coal to Hot Metal", "BSL", "", 4, 0.910),
    ("MAJOR", "Coal to Hot Metal", "ISP", "", 5, 0.883),
    ("MAJOR", "Coal to Hot Metal", "SAIL", "", 6, 0.920),
    ("MAJOR", "Coke Rate", "BSP", "kg/Thm", 10, 426),
    ("MAJOR", "Coke Rate", "DSP", "kg/Thm", 11, 473),
    ("MAJOR", "Coke Rate", "RSP", "kg/Thm", 12, 384),
    ("MAJOR", "Coke Rate", "BSL", "kg/Thm", 13, 450),
    ("MAJOR", "Coke Rate", "ISP", "kg/Thm", 14, 360),
    ("MAJOR", "Coke Rate", "SAIL", "kg/Thm", 15, 418),
    ("MAJOR", "Nut Coke Consumption", "BSP", "kg/Thm", 20, 19),
    ("MAJOR", "Nut Coke Consumption", "DSP", "kg/Thm", 21, 22),
    ("MAJOR", "Nut Coke Consumption", "RSP", "kg/Thm", 22, 19),
    ("MAJOR", "Nut Coke Consumption", "BSL", "kg/Thm", 23, 16),
    ("MAJOR", "Nut Coke Consumption", "ISP", "kg/Thm", 24, 34),
    ("MAJOR", "Nut Coke Consumption", "SAIL", "kg/Thm", 25, 21),
    ("MAJOR", "Fuel Rate", "BSP", "kg/Thm", 30, 565),
    ("MAJOR", "Fuel Rate", "DSP", "kg/Thm", 31, 550),
    ("MAJOR", "Fuel Rate", "RSP", "kg/Thm", 32, 546),
    ("MAJOR", "Fuel Rate", "BSL", "kg/Thm", 33, 554),
    ("MAJOR", "Fuel Rate", "ISP", "kg/Thm", 34, 540),
    ("MAJOR", "Fuel Rate", "SAIL", "kg/Thm", 35, 553),
    ("MAJOR", "BF Productivity (Working Volume)", "BSP", "T/m3/Day", 40, 1.99),
    ("MAJOR", "BF Productivity (Working Volume)", "DSP", "T/m3/Day", 41, 1.76),
    ("MAJOR", "BF Productivity (Working Volume)", "RSP", "T/m3/Day", 42, 2.45),
    ("MAJOR", "BF Productivity (Working Volume)", "BSL", "T/m3/Day", 43, 1.92),
    ("MAJOR", "BF Productivity (Working Volume)", "ISP", "T/m3/Day", 44, 2.40),
    ("MAJOR", "BF Productivity (Working Volume)", "SAIL", "T/m3/Day", 45, 2.08),
    ("MAJOR", "Specific Energy Consumption", "BSP", "G.Cal/Tcs", 50, 6.09),
    ("MAJOR", "Specific Energy Consumption", "DSP", "G.Cal/Tcs", 51, 6.34),
    ("MAJOR", "Specific Energy Consumption", "RSP", "G.Cal/Tcs", 52, 6.02),
    ("MAJOR", "Specific Energy Consumption", "BSL", "G.Cal/Tcs", 53, 6.54),
    ("MAJOR", "Specific Energy Consumption", "ISP", "G.Cal/Tcs", 54, 6.03),
    ("MAJOR", "Specific Energy Consumption", "SAIL", "G.Cal/Tcs", 55, 6.19),
    # COKE_SINTER
    ("COKE_SINTER", "BF Coke Yield", "BSP", "%", 1, 68.8),
    ("COKE_SINTER", "BF Coke Yield", "DSP", "%", 2, 68.5),
    ("COKE_SINTER", "BF Coke Yield", "RSP", "%", 3, 68.6),
    ("COKE_SINTER", "BF Coke Yield", "BSL", "%", 4, 69.5),
    ("COKE_SINTER", "BF Coke Yield", "ISP", "%", 5, 70.0),
    ("COKE_SINTER", "Sp. Heat Cons.", "BSP", "000 K.Cal/TDC", 10, 697),
    ("COKE_SINTER", "Sp. Heat Cons.", "DSP", "000 K.Cal/TDC", 11, 642),
    ("COKE_SINTER", "Sp. Heat Cons.", "RSP", "000 K.Cal/TDC", 12, 710),
    ("COKE_SINTER", "Sp. Heat Cons.", "BSL", "000 K.Cal/TDC", 13, 676),
    ("COKE_SINTER", "Sp. Heat Cons.", "ISP", "000 K.Cal/TDC", 14, 715),
    ("COKE_SINTER", "Coal Tar Yield", "BSP", "kg/TDC", 20, 29.2),
    ("COKE_SINTER", "Coal Tar Yield", "DSP", "kg/TDC", 21, 30.6),
    ("COKE_SINTER", "Coal Tar Yield", "RSP", "kg/TDC", 22, 32.3),
    ("COKE_SINTER", "Coal Tar Yield", "BSL", "kg/TDC", 23, 32.2),
    ("COKE_SINTER", "Coal Tar Yield", "ISP", "kg/TDC", 24, 23.7),
    ("COKE_SINTER", "Sinter Productivity", "BSP (SP-2)", "T/m2/hr", 30, 1.2),
    ("COKE_SINTER", "Sinter Productivity", "DSP SP-2", "T/m2/hr", 31, 1.4),
    ("COKE_SINTER", "Sinter Productivity", "RSP SP-2", "T/m2/hr", 32, 1.3),
    ("COKE_SINTER", "Sinter Productivity", "BSL", "T/m2/hr", 33, 1.1),
    ("COKE_SINTER", "Sinter Productivity", "ISP", "T/m2/hr", 34, 1.4),
    # IRON_MAKING
    ("IRON_MAKING", "Productivity (Working vol.)", "BSP", "T/m3/day", 1, 1.99),
    ("IRON_MAKING", "Productivity (Working vol.)", "DSP", "T/m3/day", 2, 1.76),
    ("IRON_MAKING", "Productivity (Working vol.)", "RSP", "T/m3/day", 3, 2.45),
    ("IRON_MAKING", "Productivity (Working vol.)", "BSL", "T/m3/day", 4, 1.92),
    ("IRON_MAKING", "Productivity (Working vol.)", "ISP", "T/m3/day", 5, 2.40),
    ("IRON_MAKING", "Productivity (Working vol.)", "SAIL 5 PLANT", "T/m3/day", 6, 2.08),
    ("IRON_MAKING", "CDI", "BSP Avg for CDI Fces", "Kg/Thm", 10, 120),
    ("IRON_MAKING", "CDI", "DSP Avg for CDI Fces", "Kg/Thm", 11, 55),
    ("IRON_MAKING", "CDI", "RSP Avg for CDI Fces", "Kg/Thm", 12, 143),
    ("IRON_MAKING", "CDI", "BSL Avg for CDI Fces", "Kg/Thm", 13, 87),
    ("IRON_MAKING", "CDI", "ISP BF-5", "Kg/Thm", 14, 146),
    ("IRON_MAKING", "Sinter %", "BSP", "%", 20, 65),
    ("IRON_MAKING", "Sinter %", "DSP", "%", 21, 70),
    ("IRON_MAKING", "Sinter %", "RSP", "%", 22, 73),
    ("IRON_MAKING", "Sinter %", "BSL", "%", 23, 63),
    ("IRON_MAKING", "Sinter %", "ISP", "%", 24, 71),
    ("IRON_MAKING", "Screen Loss", "BSP", "%", 30, 11.1),
    ("IRON_MAKING", "Screen Loss", "DSP", "%", 31, 12.0),
    ("IRON_MAKING", "Screen Loss", "RSP", "%", 32, 13.8),
    ("IRON_MAKING", "Screen Loss", "BSL", "%", 33, 12.4),
    ("IRON_MAKING", "Screen Loss", "ISP", "%", 34, 10.8),
    # BOF
    ("BOF", "Average Blows (Per Day)", "BSP SMS-2", "Nos.", 1, 51),
    ("BOF", "Average Blows (Per Day)", "BSP SMS-3", "Nos.", 2, 56),
    ("BOF", "Average Blows (Per Day)", "DSP SMS", "Nos.", 3, 50),
    ("BOF", "Average Blows (Per Day)", "RSP SMS-1", "Nos.", 4, 17),
    ("BOF", "Average Blows (Per Day)", "RSP SMS-2", "Nos.", 5, 61),
    ("BOF", "Average Blows (Per Day)", "BSL SMS-1", "Nos.", 6, 26),
    ("BOF", "Average Blows (Per Day)", "BSL SMS-2", "Nos.", 7, 29),
    ("BOF", "Average Blows (Per Day)", "ISP", "Nos.", 8, 49),
    ("BOF", "Average Heat Weight", "BSP SMS-2", "T", 10, 120),
    ("BOF", "Average Heat Weight", "BSP SMS-3", "T", 11, 168),
    ("BOF", "Average Heat Weight", "DSP SMS", "T", 12, 119),
    ("BOF", "Average Heat Weight", "RSP SMS-2", "T", 13, 158),
    ("BOF", "Average Heat Weight", "BSL SMS-2", "T", 14, 276),
    ("BOF", "Average Heat Weight", "ISP", "T", 15, 157),
    ("BOF", "TMI", "BSP SMS-2", "Kg/TCS", 20, 1105),
    ("BOF", "TMI", "DSP SMS", "Kg/TCS", 21, 1093),
    ("BOF", "TMI", "RSP SMS-1", "Kg/TCS", 22, 1128),
    ("BOF", "TMI", "BSL SMS-1", "Kg/TCS", 23, 1131),
    ("BOF", "TMI", "ISP SMS-1", "Kg/TCS", 24, 1097),
    ("BOF", "Oxygen Blowing", "BSP SMS-2", "Nm3/TCS", 30, 70.5),
    ("BOF", "Oxygen Blowing", "DSP SMS", "Nm3/TCS", 31, 56.8),
    ("BOF", "Oxygen Blowing", "RSP SMS-2", "Nm3/TCS", 32, 60.1),
    ("BOF", "Oxygen Blowing", "BSL SMS-1", "Nm3/TCS", 33, 52.8),
    ("BOF", "Oxygen Blowing", "ISP SMS", "Nm3/TCS", 34, 51.6),
    # MILL pages
    ("MILL_BSP", "Rail & Struc. Mill", "Overall yield", "%", 1, 90.8),
    ("MILL_BSP", "Rail & Struc. Mill", "Rolling rate", "T/Hr.", 2, 81),
    ("MILL_BSP", "Rail & Struc. Mill", "Mill availability", "%", 3, 93.7),
    ("MILL_BSP", "Rail & Struc. Mill", "Mill utilisation", "% Avl.", 4, 74.6),
    ("MILL_BSP", "Rail & Struc. Mill", "Sp. Heat Cons.", "Mcal/T", 5, 790),
    ("MILL_BSP", "Rail & Struc. Mill", "Sp. Power Cons.", "Kwh/T", 6, 77),
    ("MILL_BSP", "Merchant Mill", "Overall yield", "%", 10, 98.2),
    ("MILL_BSP", "Merchant Mill", "Rolling rate", "T/Hr.", 11, 93),
    ("MILL_BSP", "Merchant Mill", "Mill availability", "%", 12, 92.7),
    ("MILL_BSP", "Merchant Mill", "Sp. Heat Cons.", "Mcal/T", 13, 699),
    ("MILL_BSP", "Plate Mill", "Overall yield", "%", 20, 90.0),
    ("MILL_BSP", "Plate Mill", "Rolling rate (Slabs rolled)", "T/Hr.", 21, 199),
    ("MILL_BSP", "Plate Mill", "Mill availability", "%", 22, 89.6),
    ("MILL_BSP", "Plate Mill", "Sp. Heat Cons.", "Mcal/T", 23, 446),
    ("MILL_DSP", "Section Mill", "Yield", "%", 1, 89.0),
    ("MILL_DSP", "Section Mill", "Rolling Rate", "T/Hr", 2, 29.1),
    ("MILL_DSP", "Section Mill", "Mill Availability", "%", 3, 85.8),
    ("MILL_DSP", "Section Mill", "Specific Heat", "M.Cal/T", 4, 616),
    ("MILL_DSP", "Merchant Mill", "Yield", "%", 10, 96.2),
    ("MILL_DSP", "Merchant Mill", "Rolling Rate", "T/Hr.", 11, 66.2),
    ("MILL_DSP", "Merchant Mill", "Mill Availability", "%", 12, 81.4),
    ("MILL_DSP", "Merchant Mill", "Specific Heat", "M.Cal/T", 13, 353),
    ("MILL_DSP", "MSM", "Yield", "%", 20, 92.0),
    ("MILL_DSP", "MSM", "Rolling Rate", "T/Utl.Hr.", 21, 113.2),
    ("MILL_DSP", "MSM", "Mill Availability", "%", 22, 88.5),
    ("MILL_RSP", "Plate Mill", "Yield - Primes", "%", 1, 91.7),
    ("MILL_RSP", "Plate Mill", "Mill Availability", "%", 2, 82),
    ("MILL_RSP", "Plate Mill", "Rolling Rate", "T/Hr.", 3, 77),
    ("MILL_RSP", "Plate Mill", "Specific Heat", "M.Cal/T", 4, 358),
    ("MILL_RSP", "HSM-II", "H R Coil Yield", "%", 10, 97.7),
    ("MILL_RSP", "HSM-II", "Mill Availability", "%", 11, 91.6),
    ("MILL_RSP", "HSM-II", "Rolling Rate -HR Coils", "T/Hr.", 12, 383),
    ("MILL_RSP", "HSM-II", "Specific Heat", "M.Cal/T", 13, 332),
    ("MILL_RSP", "New Plate Mill", "Yield - Primes", "%", 20, 90.1),
    ("MILL_RSP", "New Plate Mill", "Rolling Rate", "T/Hr.", 21, 133),
    ("MILL_RSP", "New Plate Mill", "Specific Heat", "M.Cal/T", 22, 311),
    ("MILL_BSL", "Hot Strip Mill", "Yield of HR Coil + T.Plate", "%", 1, 96.6),
    ("MILL_BSL", "Hot Strip Mill", "Availability against Cal. Hrs", "%", 2, 97),
    ("MILL_BSL", "Hot Strip Mill", "Slab Rolling Rate", "T/Hr", 3, 693),
    ("MILL_BSL", "Hot Strip Mill", "Specific Heat", "M.Cal/T", 4, 421),
    ("MILL_BSL", "Cold Rolling Mill III", "PLTCM: Yield from HR Coil", "%", 10, 94),
    ("MILL_BSL", "Cold Rolling Mill III", "PLTCM: Utilisation", "% Avl.", 11, 96),
    ("MILL_BSL", "Cold Rolling Mill III", "Specific Power Consumption", "Kwh/T", 12, 171),
    ("MILL_ISP", "Wire Rod Mill", "% Mill Availability", "%", 1, 82),
    ("MILL_ISP", "Wire Rod Mill", "% Mill Utilisation", "%", 2, 88),
    ("MILL_ISP", "Wire Rod Mill", "Gross Heat Consumption", "M.Cal/T", 3, 335),
    ("MILL_ISP", "Wire Rod Mill", "Yield", "%", 4, 95.7),
    ("MILL_ISP", "Bar Mill", "% Mill Availability", "%", 10, 88),
    ("MILL_ISP", "Bar Mill", "Gross Heat Consumption", "M.Cal/T", 11, 256),
    ("MILL_ISP", "Bar Mill", "Yield", "%", 12, 96.4),
    ("MILL_ISP", "US Mill", "% Mill Availability", "%", 20, 83),
    ("MILL_ISP", "US Mill", "Gross Heat Consumption", "M.Cal/T", 21, 481),
    ("MILL_ISP", "US Mill", "Yield", "%", 22, 93.9),
]

# FY 24-25 sample months (annual avg), FY 25-26 (annual avg + CPLY), FY 26-27 current
MONTHS = {
    "2024-10": 1.015, "2025-03": 0.985,
    "2025-04": 1.01,  "2025-05": 0.99,
    "2026-04": 1.00,  "2026-05": 1.005,
}

# grouped per FY so each row carries its Apr-to-month cumulative
MONTHS_BY_FY = {
    2024: [("2024-10", 1.015), ("2025-03", 0.985)],
    2025: [("2025-04", 1.01),  ("2025-05", 0.99)],
    2026: [("2026-04", 1.00),  ("2026-05", 1.005)],
}

if __name__ == "__main__":
    n = 0
    for group, section, label, unit, sort, base in ROWS:
        pid = db.get_or_create_techno_param(group, section, label, unit, sort)
        for fy, entries in MONTHS_BY_FY.items():
            running = []
            for m, factor in entries:
                actual = round(base * factor, 3)
                running.append(actual)
                cum = round(sum(running) / len(running), 3)  # stand-in for plant-reported cum
                db.save_techno_value(m, pid, actual, cum)
                n += 1
        db.save_techno_target("2026-27", pid, round(base * 0.98, 3))
    print(f"{len(ROWS)} master rows, {n} monthly values (with cum), {len(ROWS)} targets")
