"""One-off seeder: techno parameter master + sample monthly values + targets.
Bases taken from the OMI Aug'25 report PDF. Safe to re-run (upserts)."""
import db

# (group, section, row_label, unit, sort, base_value)
ROWS = [
    # MAJOR  (sorts: C/HM=10, CokeRate=20, NutCoke=30, CDI=40, FuelRate=50,
    #          Sinter%=60, Pellet%=70, BFProd=80, HMCons=90, Scrap=100, TMI=110, SpecEnergy=120)
    ("MAJOR", "Coal to Hot Metal", "BSP",  "", 10, 0.948),
    ("MAJOR", "Coal to Hot Metal", "DSP",  "", 11, 0.986),
    ("MAJOR", "Coal to Hot Metal", "RSP",  "", 12, 0.881),
    ("MAJOR", "Coal to Hot Metal", "BSL",  "", 13, 0.910),
    ("MAJOR", "Coal to Hot Metal", "ISP",  "", 14, 0.883),
    ("MAJOR", "Coal to Hot Metal", "SAIL", "", 15, 0.920),
    ("MAJOR", "Coke Rate", "BSP",  "kg/Thm", 20, 426),
    ("MAJOR", "Coke Rate", "DSP",  "kg/Thm", 21, 473),
    ("MAJOR", "Coke Rate", "RSP",  "kg/Thm", 22, 384),
    ("MAJOR", "Coke Rate", "BSL",  "kg/Thm", 23, 450),
    ("MAJOR", "Coke Rate", "ISP",  "kg/Thm", 24, 360),
    ("MAJOR", "Coke Rate", "SAIL", "kg/Thm", 25, 418),
    ("MAJOR", "Nut Coke Consumption", "BSP",  "kg/Thm", 30, 19),
    ("MAJOR", "Nut Coke Consumption", "DSP",  "kg/Thm", 31, 22),
    ("MAJOR", "Nut Coke Consumption", "RSP",  "kg/Thm", 32, 19),
    ("MAJOR", "Nut Coke Consumption", "BSL",  "kg/Thm", 33, 16),
    ("MAJOR", "Nut Coke Consumption", "ISP",  "kg/Thm", 34, 34),
    ("MAJOR", "Nut Coke Consumption", "SAIL", "kg/Thm", 35, 21),
    ("MAJOR", "CDI Rate", "BSP",  "kg/Thm", 40, 130),
    ("MAJOR", "CDI Rate", "DSP",  "kg/Thm", 41,  78),
    ("MAJOR", "CDI Rate", "RSP",  "kg/Thm", 42, 140),
    ("MAJOR", "CDI Rate", "BSL",  "kg/Thm", 43, 105),
    ("MAJOR", "CDI Rate", "ISP",  "kg/Thm", 44, 150),
    ("MAJOR", "CDI Rate", "SAIL", "kg/Thm", 45, 123),
    ("MAJOR", "Fuel Rate", "BSP",  "kg/Thm", 50, 565),
    ("MAJOR", "Fuel Rate", "DSP",  "kg/Thm", 51, 550),
    ("MAJOR", "Fuel Rate", "RSP",  "kg/Thm", 52, 546),
    ("MAJOR", "Fuel Rate", "BSL",  "kg/Thm", 53, 554),
    ("MAJOR", "Fuel Rate", "ISP",  "kg/Thm", 54, 540),
    ("MAJOR", "Fuel Rate", "SAIL", "kg/Thm", 55, 553),
    ("MAJOR", "Sinter in Burden", "BSP",  "%", 60, 64),
    ("MAJOR", "Sinter in Burden", "DSP",  "%", 61, 69),
    ("MAJOR", "Sinter in Burden", "RSP",  "%", 62, 70),
    ("MAJOR", "Sinter in Burden", "BSL",  "%", 63, 56),
    ("MAJOR", "Sinter in Burden", "ISP",  "%", 64, 70),
    ("MAJOR", "Sinter in Burden", "SAIL", "%", 65, 65),
    ("MAJOR", "Pellet in Burden", "BSP",  "%", 70, 16),
    ("MAJOR", "Pellet in Burden", "DSP",  "%", 71,  0),
    ("MAJOR", "Pellet in Burden", "RSP",  "%", 72, 20),
    ("MAJOR", "Pellet in Burden", "BSL",  "%", 73, 14),
    ("MAJOR", "Pellet in Burden", "ISP",  "%", 74, 17),
    ("MAJOR", "Pellet in Burden", "SAIL", "%", 75, 15),
    ("MAJOR", "BF Productivity (Working Volume)", "BSP",  "T/m3/Day", 80, 1.99),
    ("MAJOR", "BF Productivity (Working Volume)", "DSP",  "T/m3/Day", 81, 1.76),
    ("MAJOR", "BF Productivity (Working Volume)", "RSP",  "T/m3/Day", 82, 2.45),
    ("MAJOR", "BF Productivity (Working Volume)", "BSL",  "T/m3/Day", 83, 1.92),
    ("MAJOR", "BF Productivity (Working Volume)", "ISP",  "T/m3/Day", 84, 2.40),
    ("MAJOR", "BF Productivity (Working Volume)", "SAIL", "T/m3/Day", 85, 2.08),
    ("MAJOR", "Hot Metal Consumption", "BSP SMS-2", "Kg/TCS",  90, 1025),
    ("MAJOR", "Hot Metal Consumption", "BSP SMS-3", "Kg/TCS",  91, 1030),
    ("MAJOR", "Hot Metal Consumption", "DSP SMS",   "Kg/TCS",  92, 1040),
    ("MAJOR", "Hot Metal Consumption", "RSP SMS-1", "Kg/TCS",  93, 1080),
    ("MAJOR", "Hot Metal Consumption", "RSP SMS-2", "Kg/TCS",  94, 1020),
    ("MAJOR", "Hot Metal Consumption", "BSL SMS-1", "Kg/TCS",  95, 1024),
    ("MAJOR", "Hot Metal Consumption", "BSL SMS-2", "Kg/TCS",  96, 1028),
    ("MAJOR", "Hot Metal Consumption", "ISP SMS-1", "Kg/TCS",  97, 1059),
    ("MAJOR", "Hot Metal Consumption", "SAIL",      "Kg/TCS",  98, 1033),
    ("MAJOR", "Scrap Consumption", "BSP SMS-2", "Kg/TCS", 100,  80),
    ("MAJOR", "Scrap Consumption", "BSP SMS-3", "Kg/TCS", 101,  68),
    ("MAJOR", "Scrap Consumption", "DSP SMS",   "Kg/TCS", 102,  50),
    ("MAJOR", "Scrap Consumption", "RSP SMS-1", "Kg/TCS", 103,  49),
    ("MAJOR", "Scrap Consumption", "RSP SMS-2", "Kg/TCS", 104,  79),
    ("MAJOR", "Scrap Consumption", "BSL SMS-1", "Kg/TCS", 105,  91),
    ("MAJOR", "Scrap Consumption", "BSL SMS-2", "Kg/TCS", 106,  77),
    ("MAJOR", "Scrap Consumption", "ISP SMS-1", "Kg/TCS", 107,  38),
    ("MAJOR", "Scrap Consumption", "SAIL",      "Kg/TCS", 108,  68),
    ("MAJOR", "TMI", "BSP SMS-2", "Kg/TCS", 110, 1105),
    ("MAJOR", "TMI", "BSP SMS-3", "Kg/TCS", 111, 1099),
    ("MAJOR", "TMI", "DSP SMS",   "Kg/TCS", 112, 1090),
    ("MAJOR", "TMI", "RSP SMS-1", "Kg/TCS", 113, 1129),
    ("MAJOR", "TMI", "RSP SMS-2", "Kg/TCS", 114, 1099),
    ("MAJOR", "TMI", "BSL SMS-1", "Kg/TCS", 115, 1115),
    ("MAJOR", "TMI", "BSL SMS-2", "Kg/TCS", 116, 1105),
    ("MAJOR", "TMI", "ISP SMS-1", "Kg/TCS", 117, 1097),
    ("MAJOR", "TMI", "SAIL",      "Kg/TCS", 118, 1101),
    ("MAJOR", "Specific Energy Consumption", "BSP",  "G.Cal/Tcs", 120, 6.09),
    ("MAJOR", "Specific Energy Consumption", "DSP",  "G.Cal/Tcs", 121, 6.34),
    ("MAJOR", "Specific Energy Consumption", "RSP",  "G.Cal/Tcs", 122, 6.02),
    ("MAJOR", "Specific Energy Consumption", "BSL",  "G.Cal/Tcs", 123, 6.54),
    ("MAJOR", "Specific Energy Consumption", "ISP",  "G.Cal/Tcs", 124, 6.03),
    ("MAJOR", "Specific Energy Consumption", "SAIL", "G.Cal/Tcs", 125, 6.19),
    # COKE_SINTER
    ("COKE_SINTER", "BF Coke Yield", "BSP", "%", 1, 68.8),
    ("COKE_SINTER", "BF Coke Yield", "DSP", "%", 2, 68.5),
    ("COKE_SINTER", "BF Coke Yield", "RSP", "%", 3, 68.6),
    ("COKE_SINTER", "BF Coke Yield", "BSL", "%", 4, 69.5),
    ("COKE_SINTER", "BF Coke Yield", "ISP", "%", 5, 70.0),
    ("COKE_SINTER", "Sp. Heat Cons.", "BSP", "000 K.Cal/TDC", 10, 697),
    ("COKE_SINTER", "Sp. Heat Cons.", "DSP", "000 K.Cal/TDC", 11, 642),
    ("COKE_SINTER", "Sp. Heat Cons.", "RSP", "000 K.Cal/TDC", 12, 710),
    ("COKE_SINTER", "Sp. Heat Cons.", "BSL", "000 K.Cal/TDC", 13, 676),
    ("COKE_SINTER", "Sp. Heat Cons.", "ISP", "000 K.Cal/TDC", 14, 715),
    ("COKE_SINTER", "Coal Tar Yield", "BSP", "kg/TDC", 20, 29.2),
    ("COKE_SINTER", "Coal Tar Yield", "DSP", "kg/TDC", 21, 30.6),
    ("COKE_SINTER", "Coal Tar Yield", "RSP", "kg/TDC", 22, 32.3),
    ("COKE_SINTER", "Coal Tar Yield", "BSL", "kg/TDC", 23, 32.2),
    ("COKE_SINTER", "Coal Tar Yield", "ISP", "kg/TDC", 24, 23.7),
    ("COKE_SINTER", "Sinter Productivity", "BSP (SP-2)", "T/m2/hr", 30, 1.2),
    ("COKE_SINTER", "Sinter Productivity", "DSP SP-1",  "T/m2/hr", 31, 0.87),
    ("COKE_SINTER", "Sinter Productivity", "DSP SP-2",  "T/m2/hr", 32, 1.4),
    ("COKE_SINTER", "Sinter Productivity", "RSP SP-1",  "T/m2/hr", 33, 0.74),
    ("COKE_SINTER", "Sinter Productivity", "RSP SP-2",  "T/m2/hr", 34, 1.3),
    ("COKE_SINTER", "Sinter Productivity", "RSP SP-3",  "T/m2/hr", 35, 1.28),
    ("COKE_SINTER", "Sinter Productivity", "BSL",       "T/m2/hr", 36, 1.1),
    ("COKE_SINTER", "Sinter Productivity", "ISP",       "T/m2/hr", 37, 1.4),
    # IRON_MAKING
    ("IRON_MAKING", "CDI", "BSP Plant Shop", "Kg/Thm", 10, 120),
    ("IRON_MAKING", "CDI", "DSP Plant Shop", "Kg/Thm", 11,  55),  # plant avg (reference)
    ("IRON_MAKING", "CDI", "DSP BF-2",             "Kg/Thm", 12,  46),  # furnace-wise (extracted)
    ("IRON_MAKING", "CDI", "DSP BF-3",             "Kg/Thm", 13,  40),
    ("IRON_MAKING", "CDI", "DSP BF-4",             "Kg/Thm", 14,  87),
    ("IRON_MAKING", "CDI", "RSP Plant Shop", "Kg/Thm", 15, 143),
    ("IRON_MAKING", "CDI", "BSL Plant Shop", "Kg/Thm", 16,  87),
    ("IRON_MAKING", "CDI", "ISP Plant Shop",             "Kg/Thm", 17, 146),
    ("IRON_MAKING", "CDI", "RSP BF-1",            "Kg/Thm", 18, 130),
    ("IRON_MAKING", "CDI", "RSP BF-4",            "Kg/Thm", 19, 155),
    ("IRON_MAKING", "CDI", "RSP BF-5",            "Kg/Thm", 20, 145),
    ("IRON_MAKING", "Sinter %", "BSP", "%", 21, 65),
    ("IRON_MAKING", "Sinter %", "DSP", "%", 21, 70),
    ("IRON_MAKING", "Sinter %", "RSP", "%", 22, 73),
    ("IRON_MAKING", "Sinter %", "BSL", "%", 23, 63),
    ("IRON_MAKING", "Sinter %", "ISP", "%", 24, 71),
    ("IRON_MAKING", "Coke Screen Loss", "BSP", "%", 30, 11.1),
    ("IRON_MAKING", "Coke Screen Loss", "DSP", "%", 31, 12.0),
    ("IRON_MAKING", "Coke Screen Loss", "RSP", "%", 32, 13.8),
    ("IRON_MAKING", "Coke Screen Loss", "BSL", "%", 33, 12.4),
    ("IRON_MAKING", "Coke Screen Loss", "ISP", "%", 34, 10.8),
    ("IRON_MAKING", "BOF Slag Utilisation", "DSP", "%", 41, 174),
    # Furnace-wise params — DSP (from PDF) and RSP (from Excel p18 sheet)
    ("IRON_MAKING", "BF Coke Rate",      "DSP BF-2", "Kg/T",    50, 477),
    ("IRON_MAKING", "BF Coke Rate",      "DSP BF-3", "Kg/T",    51, 483),
    ("IRON_MAKING", "BF Coke Rate",      "DSP BF-4", "Kg/T",    52, 435),
    ("IRON_MAKING", "BF Coke Rate",      "RSP BF-1", "Kg/T",    53, 390),
    ("IRON_MAKING", "BF Coke Rate",      "RSP BF-4", "Kg/T",    54, 385),
    ("IRON_MAKING", "BF Coke Rate",      "RSP BF-5", "Kg/T",    55, 378),
    ("IRON_MAKING", "Nut Coke Rate",     "DSP BF-2", "Kg/T",    60,  21),
    ("IRON_MAKING", "Nut Coke Rate",     "DSP BF-3", "Kg/T",    61,  26),
    ("IRON_MAKING", "Nut Coke Rate",     "DSP BF-4", "Kg/T",    62,  21),
    ("IRON_MAKING", "Nut Coke Rate",     "RSP BF-1", "Kg/T",    63,  20),
    ("IRON_MAKING", "Nut Coke Rate",     "RSP BF-4", "Kg/T",    64,  18),
    ("IRON_MAKING", "Nut Coke Rate",     "RSP BF-5", "Kg/T",    65,  19),
    ("IRON_MAKING", "BF Productivity",   "DSP BF-2", "T/m3/Day",70, 1.706),
    ("IRON_MAKING", "BF Productivity",   "DSP BF-3", "T/m3/Day",71, 1.776),
    ("IRON_MAKING", "BF Productivity",   "DSP BF-4", "T/m3/Day",72, 1.739),
    ("IRON_MAKING", "BF Productivity",   "RSP BF-1", "T/m3/Day",73, 2.35),
    ("IRON_MAKING", "BF Productivity",   "RSP BF-4", "T/m3/Day",74, 2.50),
    ("IRON_MAKING", "BF Productivity",   "RSP BF-5", "T/m3/Day",75, 2.55),
    ("IRON_MAKING", "Si in HM",          "DSP BF-2", "%",        80, 0.89),
    ("IRON_MAKING", "Si in HM",          "DSP BF-3", "%",        81, 0.88),
    ("IRON_MAKING", "Si in HM",          "DSP BF-4", "%",        82, 0.88),
    ("IRON_MAKING", "Si in HM",          "RSP BF-1", "%",        83, 0.90),
    ("IRON_MAKING", "Si in HM",          "RSP BF-4", "%",        84, 0.88),
    ("IRON_MAKING", "Si in HM",          "RSP BF-5", "%",        85, 0.87),
    ("IRON_MAKING", "S in HM",           "DSP BF-2", "%",        90, 0.040),
    ("IRON_MAKING", "S in HM",           "DSP BF-3", "%",        91, 0.039),
    ("IRON_MAKING", "S in HM",           "DSP BF-4", "%",        92, 0.040),
    ("IRON_MAKING", "HBT", "DSP BF-2", "°C",      100,  971),
    ("IRON_MAKING", "HBT", "DSP BF-3", "°C",      101,  924),
    ("IRON_MAKING", "HBT", "DSP BF-4", "°C",      102,  967),
    ("IRON_MAKING", "HBT", "RSP BF-1", "°C",      103, 1050),
    ("IRON_MAKING", "HBT", "RSP BF-4", "°C",      104, 1060),
    ("IRON_MAKING", "HBT", "RSP BF-5", "°C",      105, 1070),
    # SMS
    ("SMS", "Average Blows (Per Day)", "BSP SMS-2", "Nos.", 1, 51),
    ("SMS", "Average Blows (Per Day)", "BSP SMS-3", "Nos.", 2, 56),
    ("SMS", "Average Blows (Per Day)", "DSP SMS", "Nos.", 3, 50),
    ("SMS", "Average Blows (Per Day)", "RSP SMS-1", "Nos.", 4, 17),
    ("SMS", "Average Blows (Per Day)", "RSP SMS-2", "Nos.", 5, 61),
    ("SMS", "Average Blows (Per Day)", "BSL SMS-1", "Nos.", 6, 26),
    ("SMS", "Average Blows (Per Day)", "BSL SMS-2", "Nos.", 7, 29),
    ("SMS", "Average Blows (Per Day)", "ISP SMS", "Nos.", 8, 49),
    ("SMS", "Average Heat Weight", "BSP SMS-2", "T", 10, 120),
    ("SMS", "Average Heat Weight", "BSP SMS-3", "T", 11, 168),
    ("SMS", "Average Heat Weight", "DSP SMS", "T", 12, 119),
    ("SMS", "Average Heat Weight", "RSP SMS-2", "T", 13, 158),
    ("SMS", "Average Heat Weight", "BSL SMS-2", "T", 14, 276),
    ("SMS", "Average Heat Weight", "ISP SMS", "T", 15, 157),
    ("SMS", "TMI", "BSP SMS-2", "Kg/TCS", 20, 1105),
    ("SMS", "TMI", "DSP SMS", "Kg/TCS", 21, 1093),
    ("SMS", "TMI", "RSP SMS-1", "Kg/TCS", 22, 1128),
    ("SMS", "TMI", "BSL SMS-1", "Kg/TCS", 23, 1131),
    ("SMS", "TMI", "ISP SMS-1", "Kg/TCS", 24, 1097),
    ("SMS", "Oxygen Blowing", "BSP SMS-2", "Nm³/TCS", 30, 70.5),
    ("SMS", "Oxygen Blowing", "DSP SMS", "Nm³/TCS", 31, 56.8),
    ("SMS", "Oxygen Blowing", "RSP SMS-2", "Nm³/TCS", 32, 60.1),
    ("SMS", "Oxygen Blowing", "BSL SMS-1", "Nm³/TCS", 33, 52.8),
    ("SMS", "Oxygen Blowing", "ISP SMS", "Nm³/TCS", 34, 51.6),
    # MILL pages
    ("MILL_BSP", "Rail & Struc. Mill", "Overall yield", "%", 1, 90.8),
    ("MILL_BSP", "Rail & Struc. Mill", "Rolling rate", "T/Hr.", 2, 81),
    ("MILL_BSP", "Rail & Struc. Mill", "Mill availability", "%", 3, 93.7),
    ("MILL_BSP", "Rail & Struc. Mill", "Mill utilisation", "% Avl.", 4, 74.6),
    ("MILL_BSP", "Rail & Struc. Mill", "Sp. Heat Cons.", "Mcal/T", 5, 790),
    ("MILL_BSP", "Rail & Struc. Mill", "Sp. Power Cons.", "Kwh/T", 6, 77),
    ("MILL_BSP", "Merchant Mill", "Overall yield", "%", 10, 98.2),
    ("MILL_BSP", "Merchant Mill", "Rolling rate", "T/Hr.", 11, 93),
    ("MILL_BSP", "Merchant Mill", "Mill availability", "%", 12, 92.7),
    ("MILL_BSP", "Merchant Mill", "Sp. Heat Cons.", "Mcal/T", 13, 699),
    ("MILL_BSP", "Plate Mill", "Overall yield", "%", 20, 90.0),
    ("MILL_BSP", "Plate Mill", "Rolling rate (Slabs rolled)", "T/Hr.", 21, 199),
    ("MILL_BSP", "Plate Mill", "Mill availability", "%", 22, 89.6),
    ("MILL_BSP", "Plate Mill", "Sp. Heat Cons.", "Mcal/T", 23, 446),
    # Section Mill omitted — stopped
    ("MILL_DSP", "Merchant Mill", "Yield", "%", 10, 96.2),
    ("MILL_DSP", "Merchant Mill", "Rolling Rate", "T/Hr.", 11, 66.2),
    ("MILL_DSP", "Merchant Mill", "Mill Availability", "%", 12, 81.4),
    ("MILL_DSP", "Merchant Mill", "Mill Utilisation", "%Avl.", 13, 90.6),
    ("MILL_DSP", "Merchant Mill", "On ICH", "%", 14, 77.4),
    ("MILL_DSP", "Merchant Mill", "Specific Heat", "M.Cal/T", 15, 353),
    ("MILL_DSP", "Merchant Mill", "Specific Power", "KWH/T", 16, 48),
    ("MILL_DSP", "MSM", "Yield", "%", 20, 92.0),
    ("MILL_DSP", "MSM", "Rolling Rate", "T/Utl.Hr.", 21, 113.2),
    ("MILL_DSP", "MSM", "Mill Availability", "%", 22, 88.5),
    ("MILL_DSP", "MSM", "Mill Utilisation", "%Avl.", 23, 68.5),
    ("MILL_DSP", "MSM", "On ICH", "%", 24, 61.8),
    ("MILL_DSP", "MSM", "Specific Heat", "M.Cal/T", 25, 564),
    ("MILL_DSP", "MSM", "Specific Power", "KWH/T", 26, 73),
    ("MILL_DSP", "Wheel Plant", "Finished Wheel over Ingot/Round", "%", 30, 50),
    ("MILL_DSP", "Wheel Plant", "Rolling Rate", "Nos./Hr.", 31, 12),
    ("MILL_DSP", "Wheel Plant", "Forging Availability", "%", 32, 86),
    ("MILL_DSP", "Wheel Plant", "Forging Utilisation", "%Avl.", 33, 66.4),
    ("MILL_DSP", "Wheel Plant", "On ICH", "%", 34, 56.8),
    ("MILL_DSP", "Wheel Plant", "Specific Heat", "M.Cal/T", 35, 1426),
    ("MILL_DSP", "Wheel Plant", "Specific Power", "KWH/T", 36, 253),
    ("MILL_DSP", "Axle Plant", "Yield over good Bloom", "%", 40, 47),
    ("MILL_DSP", "Axle Plant", "Forging Rate", "Nos./Hr.", 41, 4),
    ("MILL_DSP", "Axle Plant", "Forging Availability", "%", 42, 86),
    ("MILL_DSP", "Axle Plant", "Forging Utilisation", "%Avl.", 43, 12.8),
    ("MILL_DSP", "Axle Plant", "On ICH", "%", 44, 11.0),
    ("MILL_DSP", "Axle Plant", "Specific Heat", "M.Cal/T", 45, 1920),
    ("MILL_DSP", "Axle Plant", "Specific Power", "KWH/T", 46, 1145),
    ("MILL_RSP", "Plate Mill",     "Yield - Primes",     "%",       1, 91.7),
    ("MILL_RSP", "Plate Mill",     "Yield - Total",      "%",       2, 94.0),
    ("MILL_RSP", "Plate Mill",     "Average Slab Weight","Tons",    3,  5.4),
    ("MILL_RSP", "Plate Mill",     "Mill Availability",  "%",       4, 82.0),
    ("MILL_RSP", "Plate Mill",     "Mill Utilisation",   "%Avl.",   5, 91.0),
    ("MILL_RSP", "Plate Mill",     "Rolling Rate",       "T/Hr.",   6, 77.0),
    ("MILL_RSP", "Plate Mill",     "Specific Heat",      "M.Cal/T", 7, 358),
    ("MILL_RSP", "Plate Mill",     "Specific Power",     "Kwh/T",   8, 70),
    ("MILL_RSP", "HSM-II",         "H R Coil Yield",         "%",       10, 97.7),
    ("MILL_RSP", "HSM-II",         "Average Slab Weight",    "Tons",    11, 23.9),
    ("MILL_RSP", "HSM-II",         "Mill Availability",      "%",       12, 91.6),
    ("MILL_RSP", "HSM-II",         "Mill Utilisation",       "%Avl.",   13, 87.0),
    ("MILL_RSP", "HSM-II",         "Rolling Rate -HR Coils", "T/Hr.",   14, 289),
    ("MILL_RSP", "HSM-II",         "Specific Heat",          "M.Cal/T", 15, 320),
    ("MILL_RSP", "HSM-II",         "Specific Power",         "Kwh/T",   16, 142),
    ("MILL_RSP", "New Plate Mill", "Yield - Primes",     "%",       20, 90.1),
    ("MILL_RSP", "New Plate Mill", "Yield - Total",      "%",       21, 89.9),
    ("MILL_RSP", "New Plate Mill", "Average Slab Weight","Tons",    22, 12.2),
    ("MILL_RSP", "New Plate Mill", "Mill Availability",  "%",       23, 92.0),
    ("MILL_RSP", "New Plate Mill", "Mill Utilisation",   "%Avl.",   24, 93.0),
    ("MILL_RSP", "New Plate Mill", "Rolling Rate",       "T/Hr.",   25, 133),
    ("MILL_RSP", "New Plate Mill", "Specific Heat",      "M.Cal/T", 26, 307),
    ("MILL_RSP", "New Plate Mill", "Specific Power",     "Kwh/T",   27, 119),
    ("MILL_RSP", "SSM",            "Yield from HRC-CRNO",     "%",      30, 90.0),
    ("MILL_RSP", "SSM",            "Acid Cons. in AP Line",   "kg/T",   31, 24.0),
    ("MILL_RSP", "SSM",            "Mill Availability",        "%",      32, 70.0),
    ("MILL_RSP", "SSM",            "Mill Utilisation",         "%Avl.",  33, 86.0),
    ("MILL_RSP", "SSM",            "Rolling Rate",             "T/Hr.",  34, 16.0),
    ("MILL_RSP", "ERW Pipe Plant", "Yield from HR Coils", "%",      40, 92.0),
    ("MILL_RSP", "ERW Pipe Plant", "Mill Availability",   "%",      41, 34.0),
    ("MILL_RSP", "ERW Pipe Plant", "Mill Utilisation",    "%Avl.",  42, 81.0),
    ("MILL_RSP", "ERW Pipe Plant", "Rolling Rate",        "T/Hr.",  43, 13.0),
    ("MILL_RSP", "SW Pipe Plant",  "Yield from HR Coils", "%",      50, 93.0),
    ("MILL_RSP", "SW Pipe Plant",  "Mill Availability",   "%",      51, 90.0),
    ("MILL_RSP", "SW Pipe Plant",  "Mill Utilisation",    "%Avl.",  52, 65.0),
    ("MILL_RSP", "SW Pipe Plant",  "Rolling Rate",        "T/Hr.",  53,  4.0),
    ("MILL_BSL", "Hot Strip Mill", "Yield of HR Coil + T.Plate", "%", 1, 96.6),
    ("MILL_BSL", "Hot Strip Mill", "Availability against Cal. Hrs", "%", 2, 97),
    ("MILL_BSL", "Hot Strip Mill", "Slab Rolling Rate", "T/Hr", 3, 693),
    ("MILL_BSL", "Hot Strip Mill", "Specific Heat", "M.Cal/T", 4, 421),
    ("MILL_BSL", "Cold Rolling Mill III", "PLTCM: Yield from HR Coil", "%", 10, 94),
    ("MILL_BSL", "Cold Rolling Mill III", "PLTCM: Utilisation", "% Avl.", 11, 96),
    ("MILL_BSL", "Cold Rolling Mill III", "Specific Power Consumption", "Kwh/T", 12, 171),
    ("MILL_ISP", "Wire Rod Mill", "% Mill Availability", "%", 1, 82),
    ("MILL_ISP", "Wire Rod Mill", "% Mill Utilisation", "%", 2, 88),
    ("MILL_ISP", "Wire Rod Mill", "Gross Heat Consumption", "M.Cal/T", 3, 335),
    ("MILL_ISP", "Wire Rod Mill", "Yield", "%", 4, 95.7),
    ("MILL_ISP", "Bar Mill", "% Mill Availability", "%", 10, 88),
    ("MILL_ISP", "Bar Mill", "Gross Heat Consumption", "M.Cal/T", 11, 256),
    ("MILL_ISP", "Bar Mill", "Yield", "%", 12, 96.4),
    ("MILL_ISP", "US Mill", "% Mill Availability", "%", 20, 83),
    ("MILL_ISP", "US Mill", "Gross Heat Consumption", "M.Cal/T", 21, 481),
    ("MILL_ISP", "US Mill", "Yield", "%", 22, 93.9),
]

# FY 24-25 sample months (annual avg), FY 25-26 (annual avg + CPLY), FY 26-27 current
MONTHS = {
    "2024-10": 1.015, "2025-03": 0.985,
    "2025-04": 1.01,  "2025-05": 0.99,
    "2026-04": 1.00,  "2026-05": 1.005,
}

# grouped per FY so each row carries its Apr-to-month cumulative
MONTHS_BY_FY = {
    2024: [("2024-10", 1.015), ("2025-03", 0.985)],
    2025: [("2025-04", 1.01),  ("2025-05", 0.99)],
    2026: [("2026-04", 1.00),  ("2026-05", 1.005)],
}

if __name__ == "__main__":
    n = 0
    for group, section, label, unit, sort, base in ROWS:
        pid = db.get_or_create_techno_param(group, section, label, unit, sort)
        for fy, entries in MONTHS_BY_FY.items():
            running = []
            for m, factor in entries:
                actual = round(base * factor, 3)
                running.append(actual)
                cum = round(sum(running) / len(running), 3)  # stand-in for plant-reported cum
                db.save_techno_value(m, pid, actual, cum)
                n += 1
        db.save_techno_target("2026-27", pid, round(base * 0.98, 3))
    print(f"{len(ROWS)} master rows, {n} monthly values (with cum), {len(ROWS)} targets")
